# Generated by Django 4.0.3 on 2022-10-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
