# Generated by Django 4.0.3 on 2022-10-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menu_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
